name: Run Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14.x', '22.x']
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          #cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        # TODO: Remove || true once sandbox API test failures are fixed
        run: npm test || true